# Generated by Django 4.1 on 2022-09-03 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_processo', models.CharField(max_length=20)),
                ('tipo_processo', models.CharField(max_length=50)),
                ('data_processo', models.DateTimeField()),
                ('logradouro', models.CharField(max_length=200)),
                ('cruzamento', models.CharField(max_length=200)),
                ('bairro', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('A INICIAR', 'A INICIAR'), ('EM ANDAMENTO', 'EM ANDAMENTO'), ('FINALIZADO', 'FINALIZADO')], default='A INICIAR', max_length=15)),
                ('coord_servico_x', models.DecimalField(decimal_places=7, max_digits=9)),
                ('coord_servico_y', models.DecimalField(decimal_places=7, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('INSTALAÇÃO', 'INSTALAÇÃO'), ('MANUTENÇÃO', 'MANUTENÇÃO'), ('REMOÇÃO', 'REMOÇÃO')], default='INSTALAÇÃO', max_length=20)),
                ('data', models.DateTimeField()),
                ('codigo_placa', models.CharField(max_length=20)),
                ('codigo_parada', models.CharField(max_length=20)),
                ('codigo_semaforo', models.IntegerField()),
                ('tipo_camera', models.CharField(choices=[('DOME', 'DOME')], default='DOME', max_length=10)),
                ('fiscalizacao', models.CharField(choices=[('SIM', 'SIM'), ('NÃO', 'NÃO')], max_length=10)),
                ('respons', models.CharField(choices=[('SEMOB', 'SEMOB'), ('TERCEIRIZADA', 'TERCEIRIZADA')], default='SEMOB', max_length=20)),
                ('quant_bastao', models.DecimalField(decimal_places=3, max_digits=5)),
                ('largura', models.DecimalField(decimal_places=3, max_digits=5)),
                ('comprim', models.DecimalField(decimal_places=3, max_digits=5)),
                ('material', models.CharField(choices=[('ACRÍLICO', 'ACRÍLICO'), ('TERMOPLASTICO', 'TERMOPLASTICO')], default='ACRÍLICO', max_length=30)),
                ('nomeclatura_placa', models.CharField(max_length=200)),
                ('diametro', models.FloatField()),
                ('area', models.FloatField()),
                ('suporte', models.CharField(choices=[('POSTE TUBO', 'POSTE TUBO'), ('POSTE ENERGISA', 'POSTE ENERGISA')], default='POSTE ENERGISA', max_length=20)),
                ('nomeclatura', models.CharField(max_length=20)),
                ('tipo_parada', models.CharField(choices=[('ABRIGO', 'ABRIGO'), ('PLACA', 'PLACA')], default='ABRIGO', max_length=20)),
                ('tipo_equipamento', models.CharField(choices=[('CAMERA', 'CAMERA'), ('CANALIZAÇÃO', 'CANALIZAÇÃO'), ('FAIXA DE PEDESTRE', 'FAIXA DE PEDESTRE'), ('EIXO', 'EIXO'), ('ESTACIONAMENTO', 'ESTACIONAMENTO'), ('ILHA', 'ILHA'), ('LOMBADA FÍSICA', 'LOMBADA FÍSICA'), ('PARADAS DE ÔNIBUS', 'PARADAS DE ÔNIBUS'), ('REDUTOR DE VELOCIDADE', 'REDUTOR DE VELOCIDADE'), ('SINALIZAÇÃO VERTICAL', 'SINALIZAÇÃO VERTICAL'), ('SEMÁFORO', 'SEMÁFORO'), ('ZEBRADO', 'ZEBRADO')], default='SINALIZAÇÃO VERTICAL', max_length=200)),
                ('quant_abrigo', models.IntegerField()),
                ('rede', models.CharField(max_length=20)),
                ('coord_inicio_eixo_x', models.DecimalField(decimal_places=7, max_digits=9)),
                ('coord_incio_eixo_y', models.DecimalField(decimal_places=7, max_digits=9)),
                ('coord_final_eixo_x', models.DecimalField(decimal_places=7, max_digits=9)),
                ('coord_final_eixo_y', models.DecimalField(decimal_places=7, max_digits=9)),
                ('processo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dsv.processo')),
            ],
        ),
    ]
